# Generated by Django 3.0.5 on 2021-05-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exception_difs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lrg_name', models.CharField(max_length=20)),
                ('dif_name', models.CharField(max_length=50)),
                ('symptom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RTI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rti_no', models.IntegerField()),
                ('rti_label', models.CharField(max_length=50)),
                ('rti_lrg', models.CharField(max_length=50)),
                ('rti_dif', models.CharField(max_length=50)),
                ('rti_symptom', models.CharField(max_length=50)),
            ],
        ),
    ]
