# Generated by Django 3.0.5 on 2021-05-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gen_difs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lrg_name', models.CharField(max_length=20)),
                ('dif_name', models.CharField(max_length=50)),
                ('rti_no', models.IntegerField()),
                ('rti_owner', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='New_difs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lrg_name', models.CharField(max_length=20)),
                ('dif_name', models.CharField(max_length=50)),
                ('rti_no', models.IntegerField()),
            ],
        ),
    ]
