# Generated by Django 3.0.5 on 2021-05-09 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_gen_difs_new_difs'),
    ]

    operations = [
        migrations.AddField(
            model_name='rti',
            name='new_dif',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='analyzer.New_difs'),
        ),
    ]
