# Generated by Django 3.0.5 on 2021-05-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_rti_new_dif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='rti',
            name='new_dif',
        ),
    ]
