# Generated by Django 3.0.5 on 2021-05-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_auto_20210509_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rti',
            name='rti_no',
            field=models.IntegerField(null=True),
        ),
    ]
