# Generated by Django 3.0.5 on 2021-05-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_auto_20210511_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='rti',
            name='rti_status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'IGNORE'), ('C', 'CRITICAL')], default='A', max_length=50),
        ),
    ]
