# Generated by Django 3.0.5 on 2021-05-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0007_rti_rti_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='signoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('lrg', models.CharField(max_length=50)),
                ('dif', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
