# Generated by Django 3.0.5 on 2021-05-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0008_signoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signoff',
            name='lrg',
            field=models.CharField(choices=[('A', 'lrgngsm'), ('B', 'lrgnfptunnel')], default='A', max_length=50),
        ),
        migrations.AlterField(
            model_name='signoff',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'IGNORE'), ('C', 'CRITICAL')], default='A', max_length=50),
        ),
    ]
