# Generated by Django 3.0.5 on 2021-05-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0009_auto_20210515_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelDrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdbms_label', models.CharField(max_length=20)),
                ('dep_label', models.CharField(max_length=50)),
                ('farm_job', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='signoff',
            name='dif',
            field=models.CharField(choices=[('A', 'a.dif'), ('B', 'b.dif')], default='A', max_length=50),
        ),
        migrations.AlterField(
            model_name='signoff',
            name='label',
            field=models.CharField(choices=[('L', 'NETWORK_MAIN_LINUX.X64_210511'), ('W', 'NETWORK_MAIN_WINDOWS.X64_210509')], default='L', max_length=20),
        ),
    ]
