# Generated by Django 3.0.5 on 2021-05-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0010_auto_20210516_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
            ],
        ),
    ]
